"""
Django settings for kapitan_chat_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_list(name, default=""):
    """Read a comma-separated environment variable into a list of strings."""
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


SPECTACULAR_SETTINGS = {
    "TITLE": "Kapitan Chat API",
    "VERSION": "1.3.0",

    "SCHEMA_PATH_PREFIX": r"/api",

    "TAGS": [
        {"name": "users", "description": "Регистрация, токены, профиль"},
        
        {"name": "chat", "description": "Чаты, сообщения, вложения"},
        {"name": "messages", "description": "Сообщения"},
        {"name": "attachments", "description": "Вложения"},

        {"name": "settings_api", "description": "Пользовательские настройки"},
    ],

    "SORT_OPERATION_TAGS": True,

    "POSTPROCESSING_HOOKS": ["kapitan_chat_backend.schema_hooks.add_tag_groups"],

    "SWAGGER_UI_SETTINGS": {
        "docExpansion": "list",
        "persistAuthorization": True,
        "plugins": [
            "SwaggerUIBundle.plugins.TagGroupsPlugin",
        ],
    },
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# NOTE: this key is shared with StorageService so it can verify JWTs issued here.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-n07b6t72v=yevg&*$=ghf3vm)wk1r@gi_&#cqhxedwvc1-y(yr',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '*')

# Behind a TLS-terminating reverse proxy (Coolify/Traefik) only plain HTTP
# reaches the container. Trust the forwarded protocol/host so Django treats
# the original request as HTTPS (needed for CSRF and secure cookies).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'drf_spectacular',
    'corsheaders',
    'chat_main_api',
    'settings_api',
    'users_api',
]
ASGI_APPLICATION = 'kapitan_chat_backend.asgi.application'

CORS_ALLOW_ALL_ORIGINS = os.environ.get('DJANGO_CORS_ALLOW_ALL', 'True').lower() in ('1', 'true', 'yes')
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = _env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

CSRF_TRUSTED_ORIGINS = _env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kapitan_chat_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://redis:6379/0')],
            "serializer_format": "json",
        },
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"  

LANGDIR = Path(MEDIA_ROOT) / 'languages'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
